sudo: true

language: cpp

os:
  - linux
  - osx

dist: trusty

before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - libatlas3gf-base
      - libatlas-dev
      - python-joblib
      - libpython-dev

install:
  - source travis_install.sh

script:
  - source run_tests.sh

cache:
  directories:
    - ${HOME}/.cache/usr

notifications:
  email:
    on_success: change
    on_failure: always
